FROM oven/bun:1.3.14 AS dependencies

WORKDIR /workspace
COPY . .
RUN bun install --frozen-lockfile

FROM dependencies AS development

WORKDIR /workspace/{{ packagePath }}
CMD ["bun", "--watch", "src/index.ts"]

FROM dependencies AS build

WORKDIR /workspace/{{ packagePath }}
RUN bun run build

FROM oven/bun:1.3.14 AS production

WORKDIR /app
COPY --from=build /workspace/{{ packagePath }}/dist ./dist
EXPOSE 3000
CMD ["bun", "dist/index.js"]
